In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

# For regression 
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [2]:
penguins = sns.load_dataset('penguins')
penguins.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [ ]:
penguins = penguins[['body_mass_g', 'bill_length_mm',
                     'sex', 'species']]
penguins.dropna(inplace = True)

In [7]:
penguins.describe()
penguins.head(5)

   body_mass_g  bill_length_mm     sex species
0       3750.0            39.1    Male  Adelie
1       3800.0            39.5  Female  Adelie
2       3250.0            40.3  Female  Adelie
4       3450.0            36.7  Female  Adelie
5       3650.0            39.3    Male  Adelie

In [8]:
# select the independent variables or features
penguins_x = penguins[['sex', 'species', 'bill_length_mm']]

# select the dependent variable
penguins_y = penguins['body_mass_g']

In [ ]:
from sklearn.model_selection import train_test_split

# devide data into training and holdout datasets
X_train, X_test, y_train, y_test = train_test_split(penguins_x, penguins_y,
                                                    test_size = 0.3, random_state = 42)

In [17]:
#regression formula 
ols_formula = 'body_mass_g ~ bill_length_mm + C(sex) + C(species)' # C() for categorical variables

ols_data = pd.concat([X_train, y_train], axis = 1)

In [ ]:
OLS = ols(ols_formula, data = ols_data)

model = OLS.fit()

model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            body_mass_g   R-squared:                       0.850
Model:                            OLS   Adj. R-squared:                  0.847
Method:                 Least Squares   F-statistic:                     322.6
Date:                Sat, 13 Jun 2026   Prob (F-statistic):           1.31e-92
Time:                        00:45:33   Log-Likelihood:                -1671.7
No. Observations:                 233   AIC:                             3353.
Df Residuals:                     228   BIC:                             3371.
Df Model:                           4
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Intercept                2032.2111    354.087      5.739      0.000    1334.510    2729.913
C(sex)[T.Male]            528.9508     55.105      9.599      0.000     420.371     637.531
C(species)[T.Chinstrap]  -285.3865    106.339     -2.684      0.008    -494.920     -75.853
C(species)[T.Gentoo]     1081.6246     94.953     11.391      0.000     894.526    1268.723
bill_length_mm             35.5505      9.493      3.745      0.000      16.845      54.256
==============================================================================
Omnibus:                        0.339   Durbin-Watson:                   1.948
Prob(Omnibus):                  0.844   Jarque-Bera (JB):                0.436
Skew:                           0.084   Prob(JB):                        0.804
Kurtosis:                       2.871   Cond. No.                         798.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""